variables:
  PROJECT_PATH: /go/src/github.com/aeramu
  PROJECT_NAME: go-graphql
  FUNCTION_NAME: graphql
  AWS_ACCESS_KEY_ID: AKIASRJURG3KTTLMXCXO
  AWS_SECRET_ACCESS_KEY: 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

stages:
  - build
  - deploy

build:
  stage: build
  image: golang:latest
  before_script:
    - mkdir -p $PROJECT_PATH
    - ln -s $CI_PROJECT_DIR $PROJECT_PATH
    - go get -v -d $PROJECT_PATH/$PROJECT_NAME
  script:
    - go build -v $PROJECT_PATH/$PROJECT_NAME/main.goS
  artifacts:
    paths:
      - main
      

deploy-lambda:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before_script:
    - apt-get install zip
    - aws configure --region ap-southeast-1 --output json
  script:
    - zip main.zip main
    - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://main.zip