variables:
  PROJECT_PATH: /src/github.com/aeramu
  PROJECT_NAME: go-graphql
  FUNCTION_NAME: graphql

stages:
 - build
 - deploy

build:
  stage: build
  image: golang:latest
  before_script:
    - mkdir -p /go/$PROJECT_PATH
    - ln -s $CI_PROJECT_DIR /go/$PROJECT_PATH
    - go get -v -d /go/$PROJECT_PATH/$PROJECT_NAME
    - cd /go/$PROJECT_PATH/$PROJECT_NAME
  script:
    - go build -v main.go

deploy-lambda:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before_script:
    - apt-get install zip
    - cd /go/$PROJECT_PATH/$PROJECT_NAME/
  script:
    - zip main.zip main
    - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://main.zip