image: golang:latest

variables:
  PROJECT_PATH: /src/github.com/aeramu
  PROJECT_NAME: go-graphql
  FUNCTION_NAME: graphql

stages:
 - test
 - build
 - deploy

build:
  stage: build
  before_script:
    - mkdir -p $GOPATH/$PROJECT_PATH
    - ln -s $CI_PROJECT_DIR $GOPATH/$PROJECT_PATH
    - go get -v -d $GOPATH/$PROJECT_PATH/$PROJECT_NAME
  script:
    - go build -v $GOPATH/$PROJECT_PATH/$PROJECT_NAME/main.go

deploy-lambda:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  before script:
    - apt-get install zip
  script:
    - zip main.zip $GOPATH/$PROJECT_PATH/$PROJECT_NAME/main
    - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://main.zip