image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

variables:
  PROJECT_PATH: /go/src/github.com/aeramu
  PROJECT_NAME: go-graphql
  FUNCTION_NAME: graphql

stages:
 - build
 - deploy

build:
  stage: build
  before_script:
    - apt-get install -y golang-go
    - mkdir -p $PROJECT_PATH
    - ln -s $CI_PROJECT_DIR $PROJECT_PATH
    - go get -v -d $PROJECT_PATH/$PROJECT_NAME
    - cd $PROJECT_PATH/$PROJECT_NAME
  script:
    - go build -v main.go

deploy-lambda:
  stage: deploy
  before_script:
    - apt-get install zip
    - cd $PROJECT_PATH/$PROJECT_NAME
  script:
    - zip main.zip main
    - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://main.zip