image: golang:latest

variables:
  APP_PATH: github.com/aeramu/go-graphql

before_script:
  - mkdir -p go/src/$APP_PATH
  - cp -r $CI_PROJECT_DIR $GOPATH/src/$APP_PATH
  - ln -s $CI_PROJECT_DIR $GOPATH/src/$APP_PATH
  - cd $GOPATH/src/$APP_PATH
  - ls
  - go get -v -d ./...

stages:
 - test
 - build
 - deploy

unit_tests:
  stage: test
  script:
    - go build -v ./...