image: golang:latest

variables:
  APP_PATH: github.com/aeramu

before_script:
  - mkdir -p $GOPATH/src/$APP_PATH
  - ln -s $CI_PROJECT_DIR $GOPATH/src/$APP_PATH
  - go get -v -d $GOPATH/src/$APP_PATH/go-graphql

stages:
 - test
 - build
 - deploy

unit_tests:
  stage: test
  script:
    - go build -v $GOPATH/src/$APP_PATH/go-graphql